name: "ZAP Baseline Scan"

on: [push]

jobs:
  zap_scan:
    runs-on: ubuntu-latest
    name: Scan the web application
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: master

      - name: Run ZAP Scan and Save HTML Report
        id: zap_scan
        uses: zaproxy/action-baseline@v0.13.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          docker_name: 'ghcr.io/zaproxy/zaproxy:stable'
          target: 'https://preview.owasp-juice.shop'
          cmd_options: '-r /github/workspace/report.html -a' # Save report to a path accessible by GitHub runner

      # List the contents of the current directory to confirm if the report exists
      - name: List files in current directory
        run: ls -la

      # Archive the HTML report if it exists
      - name: Archive ZAP HTML Report
        if: success()
        uses: actions/upload-artifact@v3
        with:
          name: zap-html-report
          path: report.html
