name: "ZAP Baseline Scan"

on: [push]

jobs:
  zap_scan:
    runs-on: ubuntu-latest
    name: Scan the web application
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: master

      - name: Run ZAP Scan and Save HTML Report
        uses: zaproxy/action-baseline@v0.13.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          docker_name: 'ghcr.io/zaproxy/zaproxy:stable'
          target: 'https://preview.owasp-juice.shop'
          cmd_options: '-r zap-results/report.html -a'

      - name: Archive ZAP HTML Report
        uses: actions/upload-artifact@v3
        with:
          name: zap-html-report
          path: zap-results/report.html
