name: "ZAP Baseline Scan"

on: [push]

jobs:
  zap_scan:
    runs-on: ubuntu-latest
    name: Scan the web application
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: master

      - name: ZAP Scan
        uses: zaproxy/action-baseline@v0.13.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          docker_name: 'ghcr.io/zaproxy/zaproxy:stable'
          target: 'https://preview.owasp-juice.shop'
          rules_file_name: '.zap/rules.tsv'
          cmd_options: '-a'
      
      - name: Save ZAP results
        run: |
          mkdir -p zap-results
          docker cp $(docker ps -q --filter ancestor=ghcr.io/zaproxy/zaproxy:stable):/zap/wrk/report.html ./zap-results/report.html
        continue-on-error: true
      
      - name: Archive ZAP Results
        uses: actions/upload-artifact@v3
        with:
          name: ZAP-report
          path: zap-results/report.html
